on:
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install NPM deps
      run: |
          npm install
    - name: Deploy BR
      env:
        HUBSPOT_PORTAL_ID: 455690
        HUBSPOT_API_KEY: ${{ secrets.HubSpotApiKey }};
    - name: Deploy INT
      env:
        HUBSPOT_PORTAL_ID: 2897528
        HUBSPOT_API_KEY: ${{ secrets.HubSpotApiKeyInter }};
      run: |
        bin/generate-config.js
        bin/deploy.sh